# Generated by Django 5.1.2 on 2024-10-19 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadside_app', '0003_ambulancetype_fueltype_towingtype_vehicle_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ambulanceservice',
            name='ambulance_types',
        ),
        migrations.RemoveField(
            model_name='ambulanceservice',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='petrolbunkservice',
            name='fuel_types',
        ),
        migrations.RemoveField(
            model_name='petrolbunkservice',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='towingservice',
            name='service_provider',
        ),
        migrations.RemoveField(
            model_name='towingservice',
            name='towing_types',
        ),
        migrations.RemoveField(
            model_name='towingservice',
            name='vehicles',
        ),
        migrations.RemoveField(
            model_name='workshopserviceprovider',
            name='services',
        ),
        migrations.RemoveField(
            model_name='workshopserviceprovider',
            name='service_provider',
        ),
        migrations.AddField(
            model_name='servicetype',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='service_type_images/'),
        ),
        migrations.DeleteModel(
            name='AmbulanceType',
        ),
        migrations.DeleteModel(
            name='AmbulanceService',
        ),
        migrations.DeleteModel(
            name='FuelType',
        ),
        migrations.DeleteModel(
            name='PetrolBunkService',
        ),
        migrations.DeleteModel(
            name='TowingType',
        ),
        migrations.DeleteModel(
            name='TowingService',
        ),
        migrations.DeleteModel(
            name='Vehicle',
        ),
        migrations.DeleteModel(
            name='WorkshopService',
        ),
        migrations.DeleteModel(
            name='WorkshopServiceProvider',
        ),
    ]
