# Generated by Django 5.0 on 2024-10-14 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadside_app', '0004_servicetype_serviceprovider'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceprovider',
            name='location',
            field=models.TextField(default=''),
        ),
    ]
