# Generated by Django 5.1.2 on 2024-10-19 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadside_app', '0004_remove_ambulanceservice_ambulance_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='image',
            field=models.ImageField(upload_to='service_type_images/'),
        ),
    ]
