# Generated by Django 5.1.2 on 2024-10-19 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadside_app', '0006_alter_servicetype_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicetype',
            name='image',
            field=models.TextField(blank=True, null=True),
        ),
    ]
