# Generated by Django 5.1.2 on 2024-10-20 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadside_app', '0008_alter_servicetype_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTypeCategory',
            fields=[
                ('category_id', models.AutoField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=100)),
                ('charge', models.CharField(blank=True, max_length=50, null=True)),
                ('price', models.CharField(blank=True, max_length=50, null=True)),
                ('service_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='roadside_app.servicetype')),
            ],
            options={
                'verbose_name_plural': 'Service Type Categories',
            },
        ),
    ]
