# Generated by Django 5.1.2 on 2024-10-20 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadside_app', '0009_servicetypecategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicetypecategory',
            name='price',
        ),
    ]
