# Generated by Django 5.1.2 on 2024-10-20 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadside_app', '0010_remove_servicetypecategory_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(help_text='Enter the location for service', max_length=255)),
                ('description', models.TextField(help_text='Describe the issue or service needed')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadside_app.serviceprovider')),
                ('service_type_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='roadside_app.servicetypecategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
