# Generated by Django 5.1.2 on 2024-10-20 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadside_app', '0014_alter_booking_status_feedback'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feedback',
        ),
    ]
