# Generated by Django 5.1.2 on 2024-11-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadside_app', '0016_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=255)),
                ('service_provider', models.CharField(max_length=255)),
                ('service_type', models.CharField(max_length=255)),
                ('charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('kilometers', models.DecimalField(decimal_places=2, max_digits=10)),
                ('additional_charge', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
