# Generated by Django 5.1.4 on 2025-01-13 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadside_app', '0018_bill_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_number', models.CharField(max_length=20)),
                ('model', models.CharField(max_length=50)),
                ('insurance_policy_number', models.CharField(max_length=30)),
                ('insurance_provider', models.CharField(max_length=50)),
                ('insurance_expiry_date', models.DateField(blank=True, null=True)),
                ('pollution_certificate_issue_date', models.DateField(blank=True, null=True)),
                ('pollution_certificate_expiry_date', models.DateField(blank=True, null=True)),
                ('road_tax_expiry_date', models.DateField()),
                ('insurance_document', models.FileField(blank=True, null=True, upload_to='documents/insurance/')),
                ('pollution_certificate_document', models.FileField(blank=True, null=True, upload_to='documents/pollution/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
