# Generated by Django 5.1.4 on 2025-01-22 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadside_app', '0020_rename_pollution_certificate_expiry_date_vehicle_pollution_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='service_provider_location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
