# Generated by Django 5.1.4 on 2025-01-23 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roadside_app', '0021_booking_service_provider_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='insurance_expiry_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='pollution_expiry_date',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='tax_expiry_date',
        ),
    ]
