# Generated by Django 5.1.4 on 2025-01-23 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roadside_app', '0024_remove_vehicle_insurance_expiry_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='insurance_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='pollution_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='tax_expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
